config/routes.rb
Rails.application.routes.draw do
  resources :surveys
  get 'surveys/new'
  get 'surveys/index'
  get 'surveys/edit'
  get 'surveys/update'
  get 'surveys/destroy'
  get 'surveys/create'

  resources :users, only: [:new, :create, :show] do
    resources :participants
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
  validates :unique_id, presence: true

  belongs_to :user
  belongs_to :survey
end

app/models/survey.rb
class Survey < ApplicationRecord

  # validates :link, presence: true, uniqueness: true

  belongs_to :user
  has_many :participants

end

app/models/user.rb
class User < ApplicationRecord
     has_secure_password

     validates :username, presence: true, uniqueness: true
     validates :password, presence: true

     has_many :surveys
     has_many :participants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
   redirect_to '/welcome' unless logged_in?
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_user

  def new
    @participant = Participant.new
    render '/participants/new'
  end

  def create
    @participant = Participant.new(participant_params)
    @participant.user_id = @user.id
    @participant.survey_id = @user.surveys.sample.id

    if @participant.save
      redirect_to user_path(id: @user.id, participant_id: @participant.id)
    else
      render '/participants/new'
    end
  end


  private

  def participant_params
    params.require(:participant).permit(:unique_id, :user_id, :survey_id)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/surveys'
    else
      flash[:warning] = "The username or password is incorrect:/"
      redirect_to login_path
    end
  end

  def login
  end

  def welcome
  end

  def page_requires_login

  end

  def destroy
    #clear the sessions[:user_id]
    puts session[:user_id]
    session.delete(:user_id)
    #params[:id] = nil
    #redirect the user back to the welcome page

    redirect_to '/welcome'
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def new
    @survey = Survey.new
    puts @survey
  end

  def index
    @surveys = current_user.surveys.all
  end

  def show
    @survey = Survey.find(params[:id])
  end


  def create
    @survey = Survey.new(survey_params)
    @survey.user_id = current_user.id
    if @survey.save!
      redirect_to @survey
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def survey_params
    params.require(:survey).permit(:link)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :show]

  def new
    @user = User.new
  end

  def show
    if params[:participant_id]
      user = User.find(params[:id])
      @participant = Participant.find_by_id(params[:participant_id])
      survey = Survey.find(@participant.survey_id)
      @random_survey_link = survey.link
    else
      redirect_to new_user_participant_path(user_id: params[:id])
    end
  end

  def create
   @user = User.new(user_params)
   if @user.save
     session[:user_id] = @user.id
     redirect_to surveys_path
   else
     flash[:warning] = "Please try again"
     redirect_to new_user_path
   end
  end

  private

  def user_params
    params.require(:user).permit(:unique_id, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participants/new.html.erb
<h1>Enter your unique id:</h1>
<%= form_for [@user, @participant] do |f|%>
  <%= f.label :number%><br>
  <%= f.text_field :unique_id%><br>
  <%= f.submit %>
<% end %>

app/views/surveys/create.html.erb
<h1>Surveys#create</h1>
<p>Find me in app/views/surveys/create.html.erb</p>

app/views/surveys/destroy.html.erb
<h1>Surveys#destroy</h1>
<p>Find me in app/views/surveys/destroy.html.erb</p>

app/views/surveys/edit.html.erb
<h1>Login</h1>
   <%= form_tag '/login' do %>
   <%= label_tag :username%>
   <%= text_field_tag :username %>
   <%= label_tag :password%>
   <%= password_field_tag :password%>
   <%= submit_tag "Login"%>
<%end%>

app/views/surveys/index.html.erb
<% if @surveys.any? %>
  <h1>ALL THE SURVEY LINKS</h1>
  <% @surveys.each do |s| %>
    <%= s.link %>
    <%= link_to "Survey Link Page", survey_path(s) %><br>
  <% end %>
<% else %>
  <h1>No survey links, yet, friend.</h1>
<% end %>

<h1>ADD A SURVEY LINK!</h1>
<%= button_to "Add a link!", "/surveys/new", method: :get%>

<h1>THIS IS YOUR SITE GENERATOR LINK</h1>
<a href="http://localhost:3000/<%= user_path(current_user.id) %>">http://localhost:3000<%= user_path(current_user.id) %></a><br><br>

<%= button_to "Logout", '/logout', method: :post%>

app/views/surveys/new.html.erb
<h1>Create a new survey link!</h1>
<%= form_for @survey do |f|%>
  <%= f.label :link%><br>
  <%= f.text_field :link%><br>
  <%= f.submit %>
<% end %>

app/views/surveys/show.html.erb
Survey Link:
<h1><%= @survey.link %></h1>

Survey Participant Count:
<p><%= @survey.participants.count%></p>

<a href="<%= surveys_path%>">Back to surveys page we must go!</a>

app/views/surveys/update.html.erb
<h1>Surveys#update</h1>
<p>Find me in app/views/surveys/update.html.erb</p>

app/views/users/new.html.erb
<% if flash[:warning] %>
    <div class="notice"><%= flash[:warning] %></div>
<% end %>

<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>
<%end%>

<p>If you meant to press the login button, I've got you:</p>
<%= button_to "Login", '/login', method: :get%>

app/views/users/show.html.erb
<h1><a href="http://localhost:3000<%= @random_survey_link %>"><%= @random_survey_link %></a></h1>